version: "3"

services:
  inkbird:
    image: jshridha/inkbird:1.1.1
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - INKBIRD_MQTT_HOST=hass.local
      - INKBIRD_MQTT_USERNAME=inkbird
      - INKBIRD_MQTT_PASSWORD=mqttpassword
      - INKBIRD_ADDRESS=90:70:65:F7:8D:AD
